// Mocks generated by Mockito 5.4.5 from annotations
// in currency_exchange/test/widget_test/home_body_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:bloc/bloc.dart' as _i8;
import 'package:currency_exchange/src/core/localizations/l10n/gen/app_localizations.g.dart'
    as _i9;
import 'package:currency_exchange/src/domain/use_case/change_currency_use_case.dart'
    as _i3;
import 'package:currency_exchange/src/domain/use_case/fetch_currency_rates_use_case.dart'
    as _i2;
import 'package:currency_exchange/src/presentation/home_page/bloc/currency_bloc.dart'
    as _i5;
import 'package:flutter/material.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFetchCurrencyRatesUseCase_0 extends _i1.SmartFake
    implements _i2.FetchCurrencyRatesUseCase {
  _FakeFetchCurrencyRatesUseCase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChangeCurrencyUseCase_1 extends _i1.SmartFake
    implements _i3.ChangeCurrencyUseCase {
  _FakeChangeCurrencyUseCase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTextEditingController_2 extends _i1.SmartFake
    implements _i4.TextEditingController {
  _FakeTextEditingController_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CurrencyBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrencyBloc extends _i1.Mock implements _i5.CurrencyBloc {
  MockCurrencyBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FetchCurrencyRatesUseCase get getCurrencyRates =>
      (super.noSuchMethod(
            Invocation.getter(#getCurrencyRates),
            returnValue: _FakeFetchCurrencyRatesUseCase_0(
              this,
              Invocation.getter(#getCurrencyRates),
            ),
          )
          as _i2.FetchCurrencyRatesUseCase);

  @override
  _i3.ChangeCurrencyUseCase get changeCurrency =>
      (super.noSuchMethod(
            Invocation.getter(#changeCurrency),
            returnValue: _FakeChangeCurrencyUseCase_1(
              this,
              Invocation.getter(#changeCurrency),
            ),
          )
          as _i3.ChangeCurrencyUseCase);

  @override
  _i4.TextEditingController get currencyController =>
      (super.noSuchMethod(
            Invocation.getter(#currencyController),
            returnValue: _FakeTextEditingController_2(
              this,
              Invocation.getter(#currencyController),
            ),
          )
          as _i4.TextEditingController);

  @override
  _i4.TextEditingController get amountController =>
      (super.noSuchMethod(
            Invocation.getter(#amountController),
            returnValue: _FakeTextEditingController_2(
              this,
              Invocation.getter(#amountController),
            ),
          )
          as _i4.TextEditingController);

  @override
  double get amount =>
      (super.noSuchMethod(Invocation.getter(#amount), returnValue: 0.0)
          as double);

  @override
  _i5.CurrencyState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i6.dummyValue<_i5.CurrencyState>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i5.CurrencyState);

  @override
  _i7.Stream<_i5.CurrencyState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i5.CurrencyState>.empty(),
          )
          as _i7.Stream<_i5.CurrencyState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void add(_i5.CurrencyEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i5.CurrencyEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i5.CurrencyState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i5.CurrencyEvent>(
    _i8.EventHandler<E, _i5.CurrencyState>? handler, {
    _i8.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i8.Transition<_i5.CurrencyEvent, _i5.CurrencyState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onChange(_i8.Change<_i5.CurrencyState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AppLocalizations].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLocalizations extends _i1.Mock implements _i9.AppLocalizations {
  MockAppLocalizations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get localeName =>
      (super.noSuchMethod(
            Invocation.getter(#localeName),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#localeName),
            ),
          )
          as String);

  @override
  String get currencyExchange =>
      (super.noSuchMethod(
            Invocation.getter(#currencyExchange),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#currencyExchange),
            ),
          )
          as String);

  @override
  String get usd =>
      (super.noSuchMethod(
            Invocation.getter(#usd),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#usd)),
          )
          as String);

  @override
  String get retry =>
      (super.noSuchMethod(
            Invocation.getter(#retry),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#retry),
            ),
          )
          as String);

  @override
  String get amount =>
      (super.noSuchMethod(
            Invocation.getter(#amount),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#amount),
            ),
          )
          as String);

  @override
  String get currency =>
      (super.noSuchMethod(
            Invocation.getter(#currency),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#currency),
            ),
          )
          as String);
}
